[window]
opacity = 1.0

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.bold_italic]
family = "FiraCodeNerdFont"
style = "Bold Italic"

[font.italic]
family = "FiraCodeNerdFont"
style = "Italic"

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/bash"

[window.dimensions]
columns = 157
lines = 38

[colors]
draw_bold_text_with_bright_colors = false

[colors.primary]
background = '0x1d2021'
foreground = '0xd5c4a1'

[colors.cursor]
text = '0x1d2021'
cursor = '0xd5c4a1'

[colors.normal]
black = '0x1d2021'
red = '0xfb4934'
green = '0xb8bb26'
yellow = '0xfabd2f'
blue = '0x83a598'
magenta = '0xd3869b'
cyan = '0x8ec07c'
white = '0xd5c4a1'

[colors.bright]
black = '0x665c54'
red = '0xfe8019'
green = '0x3c3836'
yellow = '0x504945'
blue = '0xbdae93'
magenta = '0xebdbb2'
cyan = '0xd65d0e'
white = '0xfbf1c7'
